name: Functional Tests

on: pull_request

jobs:
  jest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install packages
        run: npm ci
      - name: Jest run
        run: npm run test